version: '3.8'

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: weather-forecast-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/app/database/app.db
      - API_CACHE_TTL=300
    volumes:
      - weather_data:/app/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - weather-network

  # Для разработки (опционально)
  weather-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: weather-forecast-app-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - weather_data_dev:/app/database
    command: npm run dev
    profiles:
      - dev
    networks:
      - weather-network

volumes:
  weather_data:
    driver: local
  weather_data_dev:
    driver: local

networks:
  weather-network:
    driver: bridge